# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Index from dimension and class indicies
#' 
#' @param i_dim integer
#' @param i_class integer
#' @param n_dim integer
#' @examples
#' mnre_dim_and_class_to_index(1, 1, 1)
#' mnre_dim_and_class_to_index(2, 3, 5)
#' @return The integer index corresponding to the dimension and class indicies
#' @export
mnre_dim_and_class_to_index <- function(i_dim, i_class, n_dim) {
    .Call('_mnre_mnre_dim_and_class_to_index', PACKAGE = 'mnre', i_dim, i_class, n_dim)
}

#' Make covariance matrix
#' 
#' @param theta_mat numeric matrix
#' @param Lind unsigned integer matrix
#' @param off_diagonal numeric
#' @examples
#' \dontrun{
#' theta_mat <- matrix(1:4, ncol=2)
#' Lind <- matrix(c(rep(1, 10), rep(2, 5)), ncol=1)
#' covar_mat <- mnre_make_covar(theta_mat, Lind)
#' }
#' @return Covariance matrix for random effects
#' @export
mnre_make_covar <- function(theta_mat, Lind, off_diagonal = 0.0) {
    .Call('_mnre_mnre_make_covar', PACKAGE = 'mnre', theta_mat, Lind, off_diagonal)
}

#' Expand matrix
#' 
#' Used to duplicate the random effects coefficient matrix before applying the left factor
#' @param x1 sparse matrix
#' @param k_class integer
#' @param direction integer
#' @return Matrix expanded in the The integer index corresponding to the dimension and class indicies
#' @export
mnre_expand_matrix <- function(x1, k_class, direction) {
    .Call('_mnre_mnre_expand_matrix', PACKAGE = 'mnre', x1, k_class, direction)
}

mnre_left_covar_factor <- function(x1) {
    .Call('_mnre_mnre_left_covar_factor', PACKAGE = 'mnre', x1)
}

#' Multinomial mixed effects fit
#' 
#' Used to duplicate the random effects coefficient matrix before applying the left factor
#' @param x1 sparse matrix
#' @param k_class integer
#' @param direction integer
#' @return Matrix expanded in the The integer index corresponding to the dimension and class indicies
#' @export
mnre_fit_sparse <- function(fixed_effects, random_effects, y, theta_mat, Lind, beta_fixed, beta_random, verbose = 1L) {
    .Call('_mnre_mnre_fit_sparse', PACKAGE = 'mnre', fixed_effects, random_effects, y, theta_mat, Lind, beta_fixed, beta_random, verbose)
}

mnre_lk_penalty <- function(beta_random, theta_norm, Lind) {
    .Call('_mnre_mnre_lk_penalty', PACKAGE = 'mnre', beta_random, theta_norm, Lind)
}

mnre_lk_glm <- function(fixed_effects, random_effects, beta_fixed, beta_random, y, Lind) {
    .Call('_mnre_mnre_lk_glm', PACKAGE = 'mnre', fixed_effects, random_effects, beta_fixed, beta_random, y, Lind)
}

mnre_lk <- function(fixed_effects, random_effects, beta_fixed, beta_random, y, theta_norm, Lind) {
    .Call('_mnre_mnre_lk', PACKAGE = 'mnre', fixed_effects, random_effects, beta_fixed, beta_random, y, theta_norm, Lind)
}

mnre_mu <- function(fixed_effects, random_effects, beta_fixed, beta_random) {
    .Call('_mnre_mnre_mu', PACKAGE = 'mnre', fixed_effects, random_effects, beta_fixed, beta_random)
}

mnre_mu_x <- function(fe_x, re_x, beta_fixed, beta_random) {
    .Call('_mnre_mnre_mu_x', PACKAGE = 'mnre', fe_x, re_x, beta_fixed, beta_random)
}

mnre_step_sparse <- function(fixed_effects, random_effects, y, beta_fixed, beta_random, lambda_norm, Lind) {
    .Call('_mnre_mnre_step_sparse', PACKAGE = 'mnre', fixed_effects, random_effects, y, beta_fixed, beta_random, lambda_norm, Lind)
}

fill_mtwm_x <- function(x1, x2, mu) {
    .Call('_mnre_fill_mtwm_x', PACKAGE = 'mnre', x1, x2, mu)
}

